# Generated by Django 2.0 on 2018-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='年')),
                ('months', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='月')),
                ('days', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='日')),
                ('hours', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='时')),
                ('minutes', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='分')),
                ('seconds', models.IntegerField(db_index=True, default=0, unique=True, verbose_name='秒')),
            ],
        ),
    ]
